apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server-container
          image: steeltoeoss/eureka-server
          imagePullPolicy: IfNotPresent
          
          ports:
            - containerPort: 8761
          
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "1"
              
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: eureka-server-config
                  key: java.opts
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5

---
# ----------------------------------------------
#  SERVICE: 
# ----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  type: ClusterIP 
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761