apiVersion: apps/v1
kind: Deployment
metadata:
  name: peminjaman-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peminjaman-service
  template:
    metadata:
      labels:
        app: peminjaman-service
    spec:
      containers:
        - name: peminjaman-service-container
          image: arsitekturberbasislayanan-peminjaman-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8083
          
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          
          env:
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: spring.profile.active
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: eureka.client.serviceurl.defaultzone
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: eureka.instance.prefer_ip_address
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: spring.rabbitmq.host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: spring.rabbitmq.port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: SERVER_PORT
              value: "8083"

---
# ----------------------------------------------
#  SERVICE: 
# ----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: peminjaman-service-svc
spec:
  type: LoadBalancer
  selector:
    app: peminjaman-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083