apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: arsitekturberbasislayanan-product-service:latest
          
          imagePullPolicy: Never
          
          ports:
            - containerPort: 8082
          
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://host.docker.internal:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_RABBITMQ_HOST
              value: "host.docker.internal"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:productdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SERVER_PORT
              value: "8082"

# ----------------------------------------------
#  SERVICE: 
# ----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 8082
      targetPort: 8082